

```{r}

library(tidyverse)

```

```{r}

brother_john <- 
  tibble::tibble(
    abs_melody = c("62,64,66,62,62,64,66,62", 
                   "66,67,69, 66,67,69", 
                   "69,71,69,67,66,62,69,71,69,67,66,62",
                   "62,57,62,62,57,62",
                   "62,64,66,62,62,64,66,62,66,67,69,66,67,69,69,71,69,67,66,62,69,71,69,67,66,62,62,57,62,62,57,62"), 
    durations = c("0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5", 
                  "0.5,0.5,1,0.5,0.5,1", 
                  "0.25,0.25,0.25,0.25,0.5,0.5,0.25,0.25,0.25,0.25,0.5,0.5",
                  "0.5,0.5,1,0.5,0.5,1",
                  "0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,1,0.5,0.5,1,0.25,0.25,0.25,0.25,0.5,0.5,0.25,0.25,0.25,0.25,0.5,0.5,0.5,0.5,1,0.5,0.5,1")
  )


```


```{r}

all_meine_entchen <- 
  tibble::tibble(
    abs_melody = "62, 64, 66, 67, 69, 69, 71, 71, 71, 71, 69, 71, 71, 71, 71, 69, 67, 67, 67, 67, 66, 66, 69, 69, 69, 69, 62",
    durations = "0.25, 0.25, 0.25, 0.25, 0.5, 0.5, 0.25, 0.25, 0.25, 0.25, 1.0, 0.25, 0.25, 0.25, 0.25, 1.0, 0.25, 0.25, 0.25, 0.25, 0.5, 0.5, 0.25, 0.25, 0.25, 0.25, 1.0"
  )

```

```{r}


itembankr::create_item_bank(name = "hbd", 
                            input = "files", 
                            midi_file_dir = "mid", 
                            output = "item",
                            scale_durations_to_have_min_abs_value_of_x_seconds = NA)

file.remove('hbd_file.rda')

load('hbd_item.rda')

hbd <- item_item_bank

rm(item_item_bank)

```


```{r}

Berkowitz_easy <- Berkowitz::ngram_item_bank %>% 
  tibble::as_tibble() %>% 
  filter(arrhythmic_difficulty_percentile < 5) %>% 
  itembankr::set_item_bank_class()


```



```{r}

use_data(Berkowitz_easy, brother_john, hbd, all_meine_entchen, internal = TRUE, overwrite = TRUE, compress = "xz")


```
