
default:
  musicassessr_aws: FALSE
  no_melodies: 2
  no_long_tones: 2
  no_examples: 0
  skip_setup: TRUE

prod:
  musicassessr_aws: TRUE
  no_melodies: 2
  no_long_tones: 6
  no_examples: 2
  skip_setup: FALSE

prod_quick:
  musicassessr_aws: TRUE
  no_melodies: 2
  no_long_tones: 2
  no_examples: 0
  skip_setup: TRUE
